# Generated by Django 4.1.3 on 2022-11-23 02:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cnab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.IntegerField(
                        choices=[
                            (1, "Débito"),
                            (2, "Boleto"),
                            (3, "Financiamento"),
                            (4, "Crédito"),
                            (5, "Recebimento Empréstimo"),
                            (6, "Vendas"),
                            (7, "Recebimento TED"),
                            (8, "Recebimento DOC"),
                            (9, "Aluguel"),
                        ]
                    ),
                ),
                (
                    "date",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{1,8}$")
                        ],
                    ),
                ),
                (
                    "value",
                    models.CharField(
                        max_length=10,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{1,10}$")
                        ],
                    ),
                ),
                (
                    "CPF",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{1,11}$")
                        ],
                    ),
                ),
                ("card", models.CharField(max_length=12)),
                (
                    "hour",
                    models.CharField(
                        max_length=6,
                        validators=[
                            django.core.validators.RegexValidator("^\\d{1,6}$")
                        ],
                    ),
                ),
                ("owner", models.CharField(max_length=14)),
                ("store_name", models.CharField(max_length=19)),
                ("file", models.FileField(upload_to="uploads/")),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
